<!-- Auto-generated by Python script -->
  <xsl:if test=".='7f907515-a1bf-4513-8a38-92e1a07c539d'">
    <dc:format>ASIN</dc:format>
  </xsl:if>
  <xsl:if test=".='3187432f-9434-40a8-8782-35a111a1491e'">
    <dc:format>BNB</dc:format>
  </xsl:if>
  <xsl:if test=".='593b78cb-32f3-44d1-ba8c-63fd5e6989e6'">
    <dc:format>CODEN</dc:format>
  </xsl:if>
  <xsl:if test=".='c858e4f2-2b6b-4385-842b-60532ee34abb'">
    <dc:format>Canceled LCCN</dc:format>
  </xsl:if>
  <xsl:if test=".='5069054d-bc3a-4212-a4e8-e2013a02386f'">
    <dc:format>Cancelled GPO item number</dc:format>
  </xsl:if>
  <xsl:if test=".='fc4e3f2a-887a-46e5-8057-aeeb271a4e56'">
    <dc:format>Cancelled system control number</dc:format>
  </xsl:if>
  <xsl:if test=".='5d164f4b-0b15-4e42-ae75-cfcf85318ad9'">
    <dc:format>Control number</dc:format>
  </xsl:if>
  <xsl:if test=".='39554f54-d0bb-4f0a-89a4-e422f6136316'">
    <dc:format>DOI</dc:format>
  </xsl:if>
  <xsl:if test=".='351ebc1c-3aae-4825-8765-c6d50dbf011f'">
    <dc:format>GPO item number</dc:format>
  </xsl:if>
  <xsl:if test=".='ebfd00b6-61d3-4d87-a6d8-810c941176d5'">
    <dc:format>ISMN</dc:format>
  </xsl:if>
  <xsl:if test=".='913300b2-03ed-469a-8179-c1092c991227'">
    <dc:format>ISSN</dc:format>
  </xsl:if>
  <xsl:if test=".='fcca2643-406a-482a-b760-7a7f8aec640e'">
    <dc:format>Invalid ISBN</dc:format>
  </xsl:if>
  <xsl:if test=".='4f07ea37-6c7f-4836-add2-14249e628ed1'">
    <dc:format>Invalid ISMN</dc:format>
  </xsl:if>
  <xsl:if test=".='27fd35a6-b8f6-41f2-aa0e-9c663ceb250c'">
    <dc:format>Invalid ISSN</dc:format>
  </xsl:if>
  <xsl:if test=".='b3ea81fb-3324-4c64-9efc-7c0c93d5943c'">
    <dc:format>Invalid UPC</dc:format>
  </xsl:if>
  <xsl:if test=".='c858e4f2-2b6b-4385-842b-60732ee14abb'">
    <dc:format>LCCN</dc:format>
  </xsl:if>
  <xsl:if test=".='5860f255-a27f-4916-a830-262aa900a6b9'">
    <dc:format>Linking ISSN</dc:format>
  </xsl:if>
  <xsl:if test=".='5130aed5-1095-4fb6-8f6f-caa3d6cc7aae'">
    <dc:format>Local identifier</dc:format>
  </xsl:if>
  <xsl:if test=".='439bfbae-75bc-4f74-9fc7-b2a2d47ce3ef'">
    <dc:format>OCLC</dc:format>
  </xsl:if>
  <xsl:if test=".='2e8b3b6c-0e7d-4e48-bca2-b0b23b376af5'">
    <dc:format>Other standard identifier</dc:format>
  </xsl:if>
  <xsl:if test=".='b5d8cdc4-9441-487c-90cf-0c7ec97728eb'">
    <dc:format>Publisher or distributor number</dc:format>
  </xsl:if>
  <xsl:if test=".='37b65e79-0392-450d-adc6-e2a1f47de452'">
    <dc:format>Report number</dc:format>
  </xsl:if>
  <xsl:if test=".='3fbacad6-0240-4823-bce8-bb122cfdf229'">
    <dc:format>StEdNL</dc:format>
  </xsl:if>
  <xsl:if test=".='8e3dd25e-db82-4b06-8311-90d41998c109'">
    <dc:format>Standard technical report number</dc:format>
  </xsl:if>
  <xsl:if test=".='7e591197-f335-4afb-bc6d-a6d76ca3bace'">
    <dc:format>System control number</dc:format>
  </xsl:if>
  <xsl:if test=".='1795ea23-6856-48a5-a772-f356e16a8a6c'">
    <dc:format>UPC</dc:format>
  </xsl:if>
  <xsl:if test=".='650ef996-35e3-48ec-bf3a-a0d078a0ca37'">
    <dc:format>UkMac</dc:format>
  </xsl:if>
  <xsl:if test=".='eb7b2717-f149-4fec-81a3-deefb8f5ee6b'">
    <dc:format>URN</dc:format>
  </xsl:if>
  <xsl:if test=".='216b156b-215e-4839-a53e-ade35cb5702a'">
    <dc:format>Handle</dc:format>
  </xsl:if>
  <xsl:if test=".='8261054f-be78-422d-bd51-4ed9f33c3422'">
    <dc:format>ISBN</dc:format>
  </xsl:if>