<!-- Auto-generated by Python script -->
  <xsl:if test=".='0d9b1c3d-2d13-4f18-9472-cc1b91bf1752'">
    <dc:format>audio -- audio belt</dc:format>
  </xsl:if>
  <xsl:if test=".='5642320a-2ab9-475c-8ca2-4af7551cf296'">
    <dc:format>audio -- audio cartridge</dc:format>
  </xsl:if>
  <xsl:if test=".='6d749f00-97bd-4eab-9828-57167558f514'">
    <dc:format>audio -- audiocassette</dc:format>
  </xsl:if>
  <xsl:if test=".='485e3e1d-9f46-42b6-8c65-6bb7bd4b37f8'">
    <dc:format>audio -- audio cylinder</dc:format>
  </xsl:if>
  <xsl:if test=".='5cb91d15-96b1-4b8a-bf60-ec310538da66'">
    <dc:format>audio -- audio disc</dc:format>
  </xsl:if>
  <xsl:if test=".='7fde4e21-00b5-4de4-a90a-08a84a601aeb'">
    <dc:format>audio -- audio roll</dc:format>
  </xsl:if>
  <xsl:if test=".='7612aa96-61a6-41bd-8ed2-ff1688e794e1'">
    <dc:format>audio -- audiotape reel</dc:format>
  </xsl:if>
  <xsl:if test=".='6a679992-b37e-4b57-b6ea-96be6b51d2b4'">
    <dc:format>audio -- audio wire reel</dc:format>
  </xsl:if>
  <xsl:if test=".='a3549b8c-3282-4a14-9ec3-c1cf294043b9'">
    <dc:format>audio -- other</dc:format>
  </xsl:if>
  <xsl:if test=".='5bfb7b4f-9cd5-4577-a364-f95352146a56'">
    <dc:format>audio -- sound track reel</dc:format>
  </xsl:if>
  <xsl:if test=".='549e3381-7d49-44f6-8232-37af1cb5ecf3'">
    <dc:format>computer -- computer card</dc:format>
  </xsl:if>
  <xsl:if test=".='88f58dc0-4243-4c6b-8321-70244ff34a83'">
    <dc:format>computer -- computer chip cartridge</dc:format>
  </xsl:if>
  <xsl:if test=".='ac9de2b9-0914-4a54-8805-463686a5489e'">
    <dc:format>computer -- computer disc</dc:format>
  </xsl:if>
  <xsl:if test=".='e05f2613-05df-4b4d-9292-2ee9aa778ecc'">
    <dc:format>computer -- computer disc cartridge</dc:format>
  </xsl:if>
  <xsl:if test=".='f4f30334-568b-4dd2-88b5-db8401607daf'">
    <dc:format>computer -- computer tape cartridge</dc:format>
  </xsl:if>
  <xsl:if test=".='e5aeb29a-cf0a-4d97-8c39-7756c10d423c'">
    <dc:format>computer -- computer tape cassette</dc:format>
  </xsl:if>
  <xsl:if test=".='d16b19d1-507f-4a22-bb8a-b3f713a73221'">
    <dc:format>computer -- computer tape reel</dc:format>
  </xsl:if>
  <xsl:if test=".='f5e8210f-7640-459b-a71f-552567f92369'">
    <dc:format>computer -- online resource</dc:format>
  </xsl:if>
  <xsl:if test=".='fe1b9adb-e0cf-4e05-905f-ce9986279404'">
    <dc:format>computer -- other</dc:format>
  </xsl:if>
  <xsl:if test=".='cb3004a3-2a85-4ed4-8084-409f93d6d8ba'">
    <dc:format>microform -- aperture card</dc:format>
  </xsl:if>
  <xsl:if test=".='fc3e32a0-9c85-4454-a42e-39fca788a7dc'">
    <dc:format>microform -- microfiche</dc:format>
  </xsl:if>
  <xsl:if test=".='b72e66e2-d946-4b01-a696-8fab07051ff8'">
    <dc:format>microform -- microfiche cassette</dc:format>
  </xsl:if>
  <xsl:if test=".='fc9bfed9-2cb0-465f-8758-33af5bba750b'">
    <dc:format>microform -- microfilm cartridge</dc:format>
  </xsl:if>
  <xsl:if test=".='b71e5ec6-a15d-4261-baf9-aea6be7af15b'">
    <dc:format>microform -- microfilm cassette</dc:format>
  </xsl:if>
  <xsl:if test=".='7bfe7e83-d4aa-46d1-b2a9-f612b18d11f4'">
    <dc:format>microform -- microfilm reel</dc:format>
  </xsl:if>
  <xsl:if test=".='cb96199a-21fb-4f11-b003-99291d8c9752'">
    <dc:format>microform -- microfilm roll</dc:format>
  </xsl:if>
  <xsl:if test=".='33009ba2-b742-4aab-b592-68b27451e94f'">
    <dc:format>microform -- microfilm slip</dc:format>
  </xsl:if>
  <xsl:if test=".='788aa9a6-5f0b-4c52-957b-998266ee3bd3'">
    <dc:format>microform -- microopaque</dc:format>
  </xsl:if>
  <xsl:if test=".='a0f2612b-f24f-4dc8-a139-89c3da5a38f1'">
    <dc:format>microform -- other</dc:format>
  </xsl:if>
  <xsl:if test=".='b1c69d78-4afb-4d8b-9624-8b3cfa5288ad'">
    <dc:format>microscopic -- microscope slide</dc:format>
  </xsl:if>
  <xsl:if test=".='55d3b8aa-304e-4967-8b78-55926d7809ac'">
    <dc:format>microscopic -- other</dc:format>
  </xsl:if>
  <xsl:if test=".='6bf2154b-df6e-4f11-97d0-6541231ac2be'">
    <dc:format>projected image -- film cartridge</dc:format>
  </xsl:if>
  <xsl:if test=".='47b226c0-853c-40f4-ba2e-2bd5ba82b665'">
    <dc:format>projected image -- film cassette</dc:format>
  </xsl:if>
  <xsl:if test=".='55a66581-3921-4b50-9981-4fe53bf35e7f'">
    <dc:format>projected image -- film reel</dc:format>
  </xsl:if>
  <xsl:if test=".='f0e689e8-e62d-4aac-b1c1-198ac9114aca'">
    <dc:format>projected image -- film roll</dc:format>
  </xsl:if>
  <xsl:if test=".='53f44ae4-167b-4cc2-9a63-4375c0ad9f58'">
    <dc:format>projected image -- filmslip</dc:format>
  </xsl:if>
  <xsl:if test=".='8e04d356-2645-4f97-8de8-9721cf11ccef'">
    <dc:format>projected image -- filmstrip</dc:format>
  </xsl:if>
  <xsl:if test=".='f7107ab3-9c09-4bcb-a637-368f39e0b140'">
    <dc:format>projected image -- filmstrip cartridge</dc:format>
  </xsl:if>
  <xsl:if test=".='9166e7c9-7edb-4180-b57e-e495f551297f'">
    <dc:format>projected image -- other</dc:format>
  </xsl:if>
  <xsl:if test=".='eb860cea-b842-4a8b-ab8d-0739856f0c2c'">
    <dc:format>projected image -- overhead transparency</dc:format>
  </xsl:if>
  <xsl:if test=".='b2b39d2f-856b-4419-93d3-ed1851f91b9f'">
    <dc:format>projected image -- slide</dc:format>
  </xsl:if>
  <xsl:if test=".='7c9b361d-66b6-4e4c-ae4b-2c01f655612c'">
    <dc:format>stereographic -- other</dc:format>
  </xsl:if>
  <xsl:if test=".='e62f4860-b3b0-462e-92b6-e032336ab663'">
    <dc:format>stereographic -- stereograph card</dc:format>
  </xsl:if>
  <xsl:if test=".='c3f41d5e-e192-4828-805c-6df3270c1910'">
    <dc:format>stereographic -- stereograph disc</dc:format>
  </xsl:if>
  <xsl:if test=".='5fa3e09f-2192-41a9-b4bf-9eb8aef0af0a'">
    <dc:format>unmediated -- card</dc:format>
  </xsl:if>
  <xsl:if test=".='affd5809-2897-42ca-b958-b311f3e0dcfb'">
    <dc:format>unmediated -- flipchart</dc:format>
  </xsl:if>
  <xsl:if test=".='926662e9-2486-4bb9-ba3b-59bd2e7f2a0c'">
    <dc:format>unmediated -- object</dc:format>
  </xsl:if>
  <xsl:if test=".='2802b285-9f27-4c86-a9d7-d2ac08b26a79'">
    <dc:format>unmediated -- other</dc:format>
  </xsl:if>
  <xsl:if test=".='68e7e339-f35c-4be2-b161-0b94d7569b7b'">
    <dc:format>unmediated -- roll</dc:format>
  </xsl:if>
  <xsl:if test=".='5913bb96-e881-4087-9e71-33a43f68e12e'">
    <dc:format>unmediated -- sheet</dc:format>
  </xsl:if>
  <xsl:if test=".='8d511d33-5e85-4c5d-9bce-6e3c9cd0c324'">
    <dc:format>unmediated -- volume</dc:format>
  </xsl:if>
  <xsl:if test=".='98f0caa9-d38e-427b-9ec4-454de81a94d7'">
    <dc:format>unspecified -- unspecified</dc:format>
  </xsl:if>
  <xsl:if test=".='e3179f91-3032-43ee-be97-f0464f359d9c'">
    <dc:format>video -- other</dc:format>
  </xsl:if>
  <xsl:if test=".='132d70db-53b3-4999-bd79-0fac3b8b9b98'">
    <dc:format>video -- video cartridge</dc:format>
  </xsl:if>
  <xsl:if test=".='431cc9a0-4572-4613-b267-befb0f3d457f'">
    <dc:format>video -- videocassette</dc:format>
  </xsl:if>
  <xsl:if test=".='7f857834-b2e2-48b1-8528-6a1fe89bf979'">
    <dc:format>video -- videodisc</dc:format>
  </xsl:if>
  <xsl:if test=".='ba0d7429-7ccf-419d-8bfb-e6a1200a8d20'">
    <dc:format>video -- videotape reel</dc:format>
  </xsl:if>