<!-- Auto-generated by Python script -->
  <xsl:if test=".='3363cdb1-e644-446c-82a4-dc3a1d4395b9'">
    <dc:format>cartographic dataset</dc:format>
  </xsl:if>
  <xsl:if test=".='526aa04d-9289-4511-8866-349299592c18'">
    <dc:format>cartographic image</dc:format>
  </xsl:if>
  <xsl:if test=".='80c0c134-0240-4b63-99d0-6ca755d5f433'">
    <dc:format>cartographic moving image</dc:format>
  </xsl:if>
  <xsl:if test=".='408f82f0-e612-4977-96a1-02076229e312'">
    <dc:format>cartographic tactile image</dc:format>
  </xsl:if>
  <xsl:if test=".='e5136fa2-1f19-4581-b005-6e007a940ca8'">
    <dc:format>cartographic tactile three-dimensional form</dc:format>
  </xsl:if>
  <xsl:if test=".='2022aa2e-bdde-4dc4-90bc-115e8894b8b3'">
    <dc:format>cartographic three-dimensional form</dc:format>
  </xsl:if>
  <xsl:if test=".='df5dddff-9c30-4507-8b82-119ff972d4d7'">
    <dc:format>computer dataset</dc:format>
  </xsl:if>
  <xsl:if test=".='c208544b-9e28-44fa-a13c-f4093d72f798'">
    <dc:format>computer program</dc:format>
  </xsl:if>
  <xsl:if test=".='fbe264b5-69aa-4b7c-a230-3b53337f6440'">
    <dc:format>notated movement</dc:format>
  </xsl:if>
  <xsl:if test=".='497b5090-3da2-486c-b57f-de5bb3c2e26d'">
    <dc:format>notated music</dc:format>
  </xsl:if>
  <xsl:if test=".='a2c91e87-6bab-44d6-8adb-1fd02481fc4f'">
    <dc:format>other</dc:format>
  </xsl:if>
  <xsl:if test=".='3be24c14-3551-4180-9292-26a786649c8b'">
    <dc:format>performed music</dc:format>
  </xsl:if>
  <xsl:if test=".='9bce18bd-45bf-4949-8fa8-63163e4b7d7f'">
    <dc:format>sounds</dc:format>
  </xsl:if>
  <xsl:if test=".='c7f7446f-4642-4d97-88c9-55bae2ad6c7f'">
    <dc:format>spoken word</dc:format>
  </xsl:if>
  <xsl:if test=".='535e3160-763a-42f9-b0c0-d8ed7df6e2a2'">
    <dc:format>still image</dc:format>
  </xsl:if>
  <xsl:if test=".='efe2e89b-0525-4535-aa9b-3ff1a131189e'">
    <dc:format>tactile image</dc:format>
  </xsl:if>
  <xsl:if test=".='e6a278fb-565a-4296-a7c5-8eb63d259522'">
    <dc:format>tactile notated movement</dc:format>
  </xsl:if>
  <xsl:if test=".='a67e00fd-dcce-42a9-9e75-fd654ec31e89'">
    <dc:format>tactile notated music</dc:format>
  </xsl:if>
  <xsl:if test=".='8105bd44-e7bd-487e-a8f2-b804a361d92f'">
    <dc:format>tactile text</dc:format>
  </xsl:if>
  <xsl:if test=".='82689e16-629d-47f7-94b5-d89736cf11f2'">
    <dc:format>tactile three-dimensional form</dc:format>
  </xsl:if>
  <xsl:if test=".='6312d172-f0cf-40f6-b27d-9fa8feaf332f'">
    <dc:format>text</dc:format>
  </xsl:if>
  <xsl:if test=".='c1e95c2b-4efc-48cf-9e71-edb622cf0c22'">
    <dc:format>three-dimensional form</dc:format>
  </xsl:if>
  <xsl:if test=".='3e3039b7-fda0-4ac4-885a-022d457cb99c'">
    <dc:format>three-dimensional moving image</dc:format>
  </xsl:if>
  <xsl:if test=".='225faa14-f9bf-4ecd-990d-69433c912434'">
    <dc:format>two-dimensional moving image</dc:format>
  </xsl:if>
  <xsl:if test=".='30fffe0e-e985-4144-b2e2-1e8179bdb41f'">
    <dc:format>unspecified</dc:format>
  </xsl:if>